name: Deploy Backend

on:
  push:
    branches: [ "main" ] # Dispara quando você dá push na main

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Configurar Java
        uses: actions/setup-java@v4
        with:
          java-version: '21' # Ajuste para a sua versão (17, 21...)
          distribution: 'temurin'
          cache: 'maven'

      - name: Build do JAR
        run: ./mvnw clean package -DskipTests

      - name: Set up QEMU (Para ARM64)
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login no Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build e Push (ARM64)
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/arm64
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/portifolio-backend:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max

  deploy-to-oracle:
    needs: build-and-push
    runs-on: ubuntu-latest
    steps:
      - name: Atualizar Servidor via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd cd /projects/portifolio
            docker compose pull backend
            docker compose up -d backend
            docker image prune -f
